# Generated by Django 4.2.15 on 2025-07-18 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=16, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Phonebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
                ('description', models.CharField(max_length=255, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_phonebooks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagger_app', models.CharField(max_length=63)),
                ('tagged_app', models.CharField(max_length=63)),
                ('tagger_id', models.CharField(max_length=63)),
                ('tagged_id', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('due', models.DateTimeField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('title', models.CharField(max_length=96)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='contacts.contact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='phonebook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='contacts.phonebook'),
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phonebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='contacts.phonebook')),
            ],
            options={
                'unique_together': {('name', 'phonebook')},
            },
        ),
        migrations.CreateModel(
            name='WritePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='write_permissions', to='contacts.phonebook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='write_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'phonebook')},
            },
        ),
        migrations.CreateModel(
            name='ReadPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_permissions', to='contacts.phonebook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'phonebook')},
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.column')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='contacts.contact')),
            ],
            options={
                'unique_together': {('contact', 'column')},
            },
        ),
        migrations.CreateModel(
            name='AlterPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alter_permissions', to='contacts.phonebook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alter_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'phonebook')},
            },
        ),
    ]
