# Generated by Django 5.2 on 2025-07-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='data_type',
            field=models.CharField(choices=[('number', 'Number'), ('str', 'String')], default='string'),
            preserve_default=False,
        ),
    ]
