# Generated by Django 4.2.15 on 2025-07-12 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonebook',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_phonebooks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='alterpermission',
            unique_together={('user', 'phonebook')},
        ),
        migrations.AlterUniqueTogether(
            name='attribute',
            unique_together={('contact', 'column')},
        ),
        migrations.AlterUniqueTogether(
            name='readpermission',
            unique_together={('user', 'phonebook')},
        ),
        migrations.AlterUniqueTogether(
            name='writepermission',
            unique_together={('user', 'phonebook')},
        ),
    ]
