# Generated by Django 4.2.15 on 2025-07-02 05:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='institution',
            new_name='employer_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='location',
        ),
        migrations.AddField(
            model_name='contact',
            name='employment_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='id_number',
            field=models.CharField(default=1000000, max_length=50),
            preserve_default=False,
        ),
    ]
