# Generated by Django 4.2.15 on 2025-07-12 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_phonebook_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phonebook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='contacts.phonebook'),
        ),
        migrations.AlterUniqueTogether(
            name='column',
            unique_together={('name', 'phonebook')},
        ),
    ]
