# Generated by Django 4.2.15 on 2025-07-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_rename_institution_contact_employer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='ability',
            field=models.FloatField(default=0.0),
        ),
    ]
