# Generated by Django 5.2 on 2025-08-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_column_data_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='column',
            old_name='name',
            new_name='field',
        ),
        migrations.AlterUniqueTogether(
            name='column',
            unique_together={('field', 'phonebook')},
        ),
        migrations.AddField(
            model_name='column',
            name='type',
            field=models.CharField(choices=[('number', 'Number'), ('string', 'String')], default='string', max_length=16),
        ),
        migrations.RemoveField(
            model_name='column',
            name='data_type',
        ),
    ]
